default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gbd_dev

test:
  <<: *default
  database: gbd_test

production:
  <<: *default
  database: gbd_prod
